app:
  # Mode =================================================== #

  # MODE
  # Switches some URL paths to Relative, Absolute or CDN.
  # Options: (development|production)
  mode: development

dummy: "dummy value"
